services:
  minishell:
    build:
      context: .
      dockerfile: ./requirements/app/Dockerfile
    image: docker_minishell_image
    container_name: docker_minishell_container
    command: bash -c /minishell
    networks:
      - minishell

networks:
    minishell:
        name: minishell_network
        driver: bridge
