services:
  minishell:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: minishell
    networks:
      - minishell

networks:
    minishell:
        name: minishell_network
        driver: bridge
