services:
  minishell:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: minishell
    container_name: minishell
    ports:
      - "7681:7681"
    networks:
      - minishell

networks:
    minishell:
        name: minishell_network
        driver: bridge
