services:
  minishell:
    build:
      context: .
      dockerfile: ./requirements/app/Dockerfile
    ports:
      - "5000:5000"
    image: minishell
    container_name: minishell
    networks:
      - minishell

networks:
    minishell:
        name: minishell_network
        driver: bridge
