version: '3'

services:
  minishell:
    build:
      context: .
      dockerfile: ./requirements/app/Dockerfile
    image: srcs_minishell
    container_name: docker_minishell_container
    command: bash -c /minishell
